<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:ns1="http://www.tibco.com/pe/EngineTypes" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.tibco.com/pe/DeployedVarsType" xmlns:ns0="www.tibco.com/plugin/Sleep" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tib="http://www.tibco.com/bw/xslt/custom-functions" xmlns:pfx2="http://www.tibco.com/pe/GenerateErrorActivity/InputSchema" xmlns:pfx="http://www.tibco.com/ns/no_namespace_schema_location/Shared Resources/Schema Definitions/Common/ExceptionSchema.xsd">
    <xsd:import namespace="http://www.tibco.com/ns/no_namespace_schema_location/Shared Resources/Schema Definitions/Common/ExceptionSchema.xsd" schemaLocation="/Shared Resources/Schema Definitions/Common/ExceptionSchema.xsd"/>
    <pd:name>Error Process Subscriber Processes/Starter Process/GetDistributionListConfiguration_Update.process</pd:name>
    <pd:startName>Timer</pd:startName>
    <pd:startX>0</pd:startX>
    <pd:startY>0</pd:startY>
    <pd:returnBindings/>
    <pd:starter name="Timer">
        <pd:type>com.tibco.plugin.timer.TimerEventSource</pd:type>
        <pd:resourceType>ae.activities.timer</pd:resourceType>
        <pd:x>27</pd:x>
        <pd:y>206</pd:y>
        <config>
            <StartTime>1464881260000</StartTime>
            <Frequency>false</Frequency>
            <TimeInterval>%%RetryConfig/GLB_GETDISTIBUTION%%</TimeInterval>
            <FrequencyIndex>Millisecond</FrequencyIndex>
        </config>
        <pd:inputBindings/>
    </pd:starter>
    <pd:endName>End</pd:endName>
    <pd:endX>712</pd:endX>
    <pd:endY>204</pd:endY>
    <pd:errorSchemas>
        <Exception ref="pfx:Exception"/>
    </pd:errorSchemas>
    <pd:processVariables/>
    <pd:targetNamespace>http://xmlns.example.com/1431727518477</pd:targetNamespace>
    <pd:group name="Group">
        <pd:type>com.tibco.pe.core.LoopGroup</pd:type>
        <pd:resourceType>ae.process.group</pd:resourceType>
        <pd:x>165</pd:x>
        <pd:y>17</pd:y>
        <pd:width>408</pd:width>
        <pd:height>358</pd:height>
        <pd:collapsedWidth>57</pd:collapsedWidth>
        <pd:collapsedHeight>70</pd:collapsedHeight>
        <pd:groupVariables/>
        <pd:joinToggle>inherit</pd:joinToggle>
        <config>
            <pd:groupType>errorLoop</pd:groupType>
            <pd:serializable>false</pd:serializable>
            <pd:indexSlot>count</pd:indexSlot>
            <pd:errorCondition>$count &gt;= $_globalVariables/ns:GlobalVariables/RetryConfig/GLB_MAX_RETRIES</pd:errorCondition>
            <pd:suspendAfterErrorRetry>true</pd:suspendAfterErrorRetry>
        </config>
        <pd:inputBindings/>
        <pd:expanded>true</pd:expanded>
        <pd:transition>
            <pd:from>start</pd:from>
            <pd:to>JDBC_GetCatalog</pd:to>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>always</pd:conditionType>
        </pd:transition>
        <pd:transition>
            <pd:from>Validate Error</pd:from>
            <pd:to>end</pd:to>
            <pd:xpathDescription>Is Error Data</pd:xpathDescription>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>xpath</pd:conditionType>
            <pd:xpath>$Validate-Error/ErrorCode='true'</pd:xpath>
        </pd:transition>
        <pd:transition>
            <pd:from>SetEmailCatalog</pd:from>
            <pd:to>end</pd:to>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>always</pd:conditionType>
        </pd:transition>
        <pd:transition>
            <pd:from>JDBC_GetCatalog</pd:from>
            <pd:to>SetEmailCatalog</pd:to>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>always</pd:conditionType>
        </pd:transition>
        <pd:transition>
            <pd:from>Catch</pd:from>
            <pd:to>Validate Error</pd:to>
            <pd:xpathDescription>Is Error</pd:xpathDescription>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-65536</pd:lineColor>
            <pd:conditionType>always</pd:conditionType>
        </pd:transition>
        <pd:transition>
            <pd:from>Validate Error</pd:from>
            <pd:to>Sleep</pd:to>
            <pd:xpathDescription>Is Technical Error</pd:xpathDescription>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>otherwise</pd:conditionType>
        </pd:transition>
        <pd:transition>
            <pd:from>Sleep</pd:from>
            <pd:to>Generate Error</pd:to>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>otherwise</pd:conditionType>
        </pd:transition>
        <pd:transition>
            <pd:from>Sleep</pd:from>
            <pd:to>Error Process</pd:to>
            <pd:xpathDescription>Count = 3</pd:xpathDescription>
            <pd:lineType>Default</pd:lineType>
            <pd:lineColor>-16777216</pd:lineColor>
            <pd:conditionType>xpath</pd:conditionType>
            <pd:xpath>$count &gt;=  $_globalVariables/ns:GlobalVariables/RetryConfig/GLB_MAX_RETRIES</pd:xpath>
        </pd:transition>
        <pd:activity name="JDBC_GetCatalog">
            <pd:type>com.tibco.plugin.jdbc.JDBCQueryActivity</pd:type>
            <pd:resourceType>ae.activities.JDBCQueryActivity</pd:resourceType>
            <pd:x>229</pd:x>
            <pd:y>76</pd:y>
            <config>
                <timeout>%%Connections/Database/JDBC_SXD201080/GLB_TIMEOUT%%</timeout>
                <commit>false</commit>
                <maxRows>%%Connections/Database/JDBC_SXD201080/GLB_MAX_ROWS%%</maxRows>
                <emptyStrAsNil>false</emptyStrAsNil>
                <statement>select	distinct
		tg.project_name,
		tg.group_name,
		tu.email  
from	tib_user_group tug inner join 
		tib_user tu on tug.id_user = tu.id_user inner join 
		dbo.tib_group tg on tug.id_group = tg.id_group</statement>
                <jdbcSharedConfig>/Shared Resources/Connections/Database/JDBC_SXD201080.sharedjdbc</jdbcSharedConfig>
                <oraObjects/>
                <oraTables/>
                <QueryOutputCachedSchemaColumns>project_name</QueryOutputCachedSchemaColumns>
                <QueryOutputCachedSchemaDataTypes>12</QueryOutputCachedSchemaDataTypes>
                <QueryOutputCachedSchemaDataTypesName>varchar</QueryOutputCachedSchemaDataTypesName>
                <QueryOutputCachedSchemaStatus>RequiredElement</QueryOutputCachedSchemaStatus>
                <QueryOutputCachedSchemaColumns>group_name</QueryOutputCachedSchemaColumns>
                <QueryOutputCachedSchemaDataTypes>12</QueryOutputCachedSchemaDataTypes>
                <QueryOutputCachedSchemaDataTypesName>varchar</QueryOutputCachedSchemaDataTypesName>
                <QueryOutputCachedSchemaStatus>RequiredElement</QueryOutputCachedSchemaStatus>
                <QueryOutputCachedSchemaColumns>email</QueryOutputCachedSchemaColumns>
                <QueryOutputCachedSchemaDataTypes>12</QueryOutputCachedSchemaDataTypes>
                <QueryOutputCachedSchemaDataTypesName>varchar</QueryOutputCachedSchemaDataTypesName>
                <QueryOutputCachedSchemaStatus>OptionalElement</QueryOutputCachedSchemaStatus>
            </config>
            <pd:inputBindings>
                <jdbcQueryActivityInput/>
            </pd:inputBindings>
        </pd:activity>
        <pd:activity name="SetEmailCatalog">
            <pd:type>com.tibco.pe.core.SetSharedVariableActivity</pd:type>
            <pd:resourceType>ae.activities.setSharedVariable</pd:resourceType>
            <pd:x>511</pd:x>
            <pd:y>77</pd:y>
            <config>
                <showResult>true</showResult>
                <variableConfig>/Shared Resources/SharedVariable/EmailCatalog.sharedvariable</variableConfig>
            </config>
            <pd:inputBindings>
                <EmailCatalog>
                    <xsl:for-each select="$JDBC_GetCatalog/resultSet/Record">
                        <EmailTypeProject>
                            <Project>
                                <xsl:value-of select="project_name"/>
                            </Project>
                            <Email>
                                <xsl:value-of select="email"/>
                            </Email>
                            <ExceptionType>
                                <xsl:value-of select="group_name"/>
                            </ExceptionType>
                        </EmailTypeProject>
                    </xsl:for-each>
                </EmailCatalog>
            </pd:inputBindings>
        </pd:activity>
        <pd:activity name="Validate Error">
            <pd:type>com.tibco.plugin.mapper.MapperActivity</pd:type>
            <pd:resourceType>ae.activities.MapperActivity</pd:resourceType>
            <pd:x>373</pd:x>
            <pd:y>203</pd:y>
            <config>
                <element>
                    <xsd:element name="ErrorCode" type="xsd:string"/>
                </element>
            </config>
            <pd:inputBindings>
                <ErrorCode>
                    <xsl:value-of select="contains($_globalVariables/ns:GlobalVariables/ExceptionHandling/GLB_CONDITION_FOR_DATA_ERROR, $_error/ns1:ErrorReport/MsgCode)"/>
                </ErrorCode>
            </pd:inputBindings>
        </pd:activity>
        <pd:activity name="Catch">
            <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
            <pd:resourceType>ae.activities.catch</pd:resourceType>
            <pd:x>370</pd:x>
            <pd:y>103</pd:y>
            <pd:handler>true</pd:handler>
            <config>
                <catchAll>true</catchAll>
            </config>
            <pd:inputBindings/>
        </pd:activity>
        <pd:activity name="Sleep">
            <pd:type>com.tibco.plugin.timer.SleepActivity</pd:type>
            <pd:resourceType>ae.activities.sleep</pd:resourceType>
            <pd:x>376</pd:x>
            <pd:y>321</pd:y>
            <config/>
            <pd:inputBindings>
                <ns0:SleepInputSchema>
                    <IntervalInMillisec>
                        <xsl:value-of select="$_globalVariables/ns:GlobalVariables/RetryConfig/GLB_RETRY_DELAY"/>
                    </IntervalInMillisec>
                </ns0:SleepInputSchema>
            </pd:inputBindings>
        </pd:activity>
        <pd:activity name="Generate Error">
            <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
            <pd:resourceType>ae.activities.throw</pd:resourceType>
            <pd:x>219</pd:x>
            <pd:y>321</pd:y>
            <config>
                <faultName/>
            </config>
            <pd:inputBindings>
                <pfx2:ActivityInput>
                    <xsl:if test="$_error/ns1:ErrorReport/Msg">
                        <message>
                            <xsl:value-of select="$_error/ns1:ErrorReport/Msg"/>
                        </message>
                    </xsl:if>
                    <xsl:if test="$_error/ns1:ErrorReport/MsgCode">
                        <messageCode>
                            <xsl:value-of select="$_error/ns1:ErrorReport/MsgCode"/>
                        </messageCode>
                    </xsl:if>
                </pfx2:ActivityInput>
            </pd:inputBindings>
        </pd:activity>
        <pd:activity name="Error Process">
            <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
            <pd:resourceType>ae.process.subprocess</pd:resourceType>
            <pd:x>519</pd:x>
            <pd:y>320</pd:y>
            <config>
                <processName>/Utility Services/Exception Handling/ErrorProcess.process</processName>
            </config>
            <pd:inputBindings>
                <Exception>
                    <Domain>
                        <xsl:value-of select="$_globalVariables/ns:GlobalVariables/Domain"/>
                    </Domain>
                    <Deployment>
                        <xsl:value-of select="$_globalVariables/ns:GlobalVariables/Deployment"/>
                    </Deployment>
                    <Project>
                        <xsl:value-of select="$_processContext/ns1:ProcessContext/ProjectName"/>
                    </Project>
                    <EngineName>
                        <xsl:value-of select="$_processContext/ns1:ProcessContext/EngineName"/>
                    </EngineName>
                    <TimeStamp>
                        <xsl:value-of select="tib:format-dateTime('yyyy-MM-dd HH:mm:ss', current-dateTime())"/>
                    </TimeStamp>
                    <xsl:if test="$_error/ns1:ErrorReport/MsgCode">
                        <Code>
                            <xsl:value-of select="$_error/ns1:ErrorReport/MsgCode"/>
                        </Code>
                    </xsl:if>
                    <Message>
                        <xsl:value-of select="tib:render-xml($_error/ns1:ErrorReport,0,0)"/>
                    </Message>
                </Exception>
            </pd:inputBindings>
        </pd:activity>
    </pd:group>
    <pd:activity name="Generate-Error-1">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>370</pd:x>
        <pd:y>472</pd:y>
        <config>
            <faultName>Exception</faultName>
        </config>
        <pd:inputBindings>
            <pfx2:ActivityInput>
                <xsl:if test="$_error/ns1:ErrorReport/Msg">
                    <message>
                        <xsl:value-of select="$_error/ns1:ErrorReport/Msg"/>
                    </message>
                </xsl:if>
                <xsl:if test="$_error/ns1:ErrorReport/MsgCode">
                    <messageCode>
                        <xsl:value-of select="$_error/ns1:ErrorReport/MsgCode"/>
                    </messageCode>
                </xsl:if>
                <data>
                    <Exception>
                        <Domain>
                            <xsl:value-of select="$_globalVariables/ns:GlobalVariables/Domain"/>
                        </Domain>
                        <Deployment>
                            <xsl:value-of select="$_globalVariables/ns:GlobalVariables/Deployment"/>
                        </Deployment>
                        <Project>
                            <xsl:value-of select="$_processContext/ns1:ProcessContext/ProjectName"/>
                        </Project>
                        <EngineName>
                            <xsl:value-of select="$_processContext/ns1:ProcessContext/EngineName"/>
                        </EngineName>
                        <TimeStamp>
                            <xsl:value-of select="tib:format-dateTime('yyyy-MM-dd HH:mm:ss', current-dateTime())"/>
                        </TimeStamp>
                        <xsl:if test="$_error/ns1:ErrorReport/MsgCode">
                            <Code>
                                <xsl:value-of select="$_error/ns1:ErrorReport/MsgCode"/>
                            </Code>
                        </xsl:if>
                        <Message>
                            <xsl:value-of select="tib:render-xml($_error/ns1:ErrorReport, 0,0)"/>
                        </Message>
                    </Exception>
                </data>
            </pfx2:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch-1">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>712</pd:x>
        <pd:y>502</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=Exception</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Error-Process-1">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>710</pd:x>
        <pd:y>371</pd:y>
        <config>
            <processName>/Utility Services/Exception Handling/ErrorProcess.process</processName>
        </config>
        <pd:inputBindings>
            <xsl:copy-of select="$Catch-1/Exception"/>
        </pd:inputBindings>
    </pd:activity>
    <pd:transition>
        <pd:from>Group</pd:from>
        <pd:to>End</pd:to>
        <pd:xpathDescription>No Error</pd:xpathDescription>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>xpath</pd:conditionType>
        <pd:xpath>not(exists($_error))</pd:xpath>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch-1</pd:from>
        <pd:to>Error-Process-1</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Error-Process-1</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Group</pd:from>
        <pd:to>Generate-Error-1</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>otherwise</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Timer</pd:from>
        <pd:to>Group</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>